spring.application.name=MedSync

spring.datasource.url=jdbc:mysql://localhost:3306/medsync_db
spring.datasource.username=root
spring.datasource.password=1234

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=6969

jwt.secret-key=UlyssesRoineIllPogiUlyssesRoineIllPogiUlyssesRoineIllPogiUlyssesRoineIllPogi

