spring.application.name=MedSync

# Database settings
spring.datasource.url=jdbc:mysql://localhost:3310/medsync_db
spring.datasource.username=root
spring.datasource.password=1234

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Server
server.port=6969

# JWT secret
jwt.secret-key=UlyssesRoineIllPogiUlyssesRoineIllPogiUlyssesRoineIllPogiUlyssesRoineIllPogi

frontend.url=http://192.168.0.102:5173
spring.mail.username=medsyncsg@gmail.com
spring.mail.password=yxerapxrhiiwhggj
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
